### PR TITLE
Add EN and JP localisation

### PR DESCRIPTION
**Pull request by danirukun**
This is the first step to localising the website.
Uses https://github.com/sveltekit-i18n/lib

### CODE REVIEW

**Comment by danirukun** [comment]
All necessary EN keys are added, and all templates changed. All that is left is JP keys.

**Comment by danirukun** [comment]
@KentoNishi how's the content review going?

**Comment by KentoNishi** [comment]
I ain't even gon lie I have so much stuff going on that I haven't even started lmao I'm so sorry I swear I'll get to it

**Comment by danirukun** [comment]
@KentoNishi did you get a chance to review the content?

**Comment by KentoNishi** [comment]
most of the strings are generally ok i think!

**Review by KentoNishi — APPROVED** [review]

**Comment by danirukun** [comment]
Pippa's profile pic seems to be broken, but it can be fixed in the main branch later.
All keys are fully localised for EN and JP.

**Comment by danirukun** [comment]
@KentoNishi any progress on the review?

**Comment by KentoNishi** [comment]
@DaniruKun it's ready to merge!

**Pull request merged**
